import { Darker_Grotesque, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import localFont from "next/font/local";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const clashDisplay = localFont({
  src: [
    {
      path: "../public/fonts/ClashDisplay-Variable.woff2",
      weight: "200 700",
      style: "normal",
    },
  ],
  variable: "--font-clash-display",
});

const darkerGrotesque = Darker_Grotesque({
  variable: "--font-darker-grotesque",
  subsets: ["latin"],
});

export const metadata = {
  title: "GDG AISSMS College of Engineering",
  description:
    "Join GDG On Campus AISSMS College of Engineering, Pune. Explore tech events, coding workshops, and developer communities.Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={clashDisplay.variable}>
      <body className={`${darkerGrotesque.variable} antialiased page`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
